### ISSUE TITLE
Inline Approvals

### ISSUE THREAD

**Issue by nitsanavni** [approvals/ApprovalTests.Python#126]
# Backgroung and Motivation

> Testing should feel like work in a REPL that we persist.
> [Michael Feathers](https://twitter.com/mfeathers/status/1614327444647071745?s=20&t=Bwuk0Cpm9ZPAW-dfoD13vA)

I'm finding the fact that approval tests "live" in two separate files (the test code file, and the approved file) to be a slight challenge.

_What if_ we could see them at once while reading tests?

I think it might have the following benefits:
- Approval tests would _look_ a little more like other kinds of tests, making them feel more familiar to new users, helping the spread of the practice
- Less jumping around between files
- Tests are more readable and understandable, at a glance

## Most Approved Files are Short

In our own repo, we currently have about **153** approved files in total.

```shell
$ find . -name '*approved*' | wc
    153     153   12591
```

Out of which only about **30** have more than 10 lines

```shell
$ find . -name '*approved*' | xargs wc 2> /dev/null | grep -sP '^ +\d{1} ' | wc
    124     496   13082
```

# How can this be done?

There must be many ways to achieve this goal, here are some ideas.

Here are a few existing implementations:
- my own [proof of concept](https://github.com/nitsanavni/katas/blob/main/inline-git-index-approvals/index.ts)
- jest has [inline snapshots](https://jestjs.io/docs/snapshot-testing#inline-snapshots)
- [a cool blog post](https://blog.janestreet.com/the-joy-of-expect-tests/) on the matter, which programming language is that BTW?

## IDE Integration

- A keyboard shortcut taking you back and forth between a test method and its approved file
- A pop-up window in the IDE showing a preview of the approved file

## Snippets

🤔

- Approved strings are added as comments after the `verify` method
- Less clutter - just the first 4 lines of approved strings are added as comments after the `verify` method

## Approved strings live in the code beside their `verify` method

- The diff tool could be triggered with specific line numbers - comparing **parts** of the test file containing the currently approved string with the received file

**Comment by gregorriegler** [comment]
I love the Idea.

Having a test-case split in more than one files is definitely a challenge.
Specifically for people just getting into testing.
I would not recommend it for people learning unit-testing just because of this fact.
It's much easier to run and explain something small that's entirely visible in one paragraph.

Ideally, I would like to see the results in the editor below the test-case in a distinguishable style.
But I'm afraid that's not easily doable with the editors we use.
Another idea would be to create a file-type that holds both python test-code and an approved result (maybe just one test-case per file). But again, that's already super complicated.
Yet another Idea would be an IDE plugin that can embed both a test-case and the corresponding results in two different text-areas. Again, complicated, probably clunky and not portable.
Another Idea: What if there was a way to write an approval test case, so that on the first run it would change the test-code and add an equals verification with the received text as a multi-line string. So it would change the code through AST manipulation, but only if you used a specific verify function. Maybe complicated. You'd only want to use this to verify short text.

**Comment by nitsanavni** [comment]
Thanks Gregor!!

About the multi-line sting in the test code:
- no need for AST manipulation if the diff tool is opened with the right line numbers to compare
- if the string is very long - it could be "folded" / "collapsed" in the IDE to make it more manageable

**Comment by nitsanavni** [comment]
I just learned there's a thing called [Inline Snapshots](https://jestjs.io/docs/snapshot-testing#inline-snapshots); Seems like what I was imagining.

**Comment by isidore** [comment]
@nitsanavni @gregorriegler This feature already exists:
[Sample here](https://github.com/approvals/ApprovalTests.Python/blob/main/tests/test_asserts.py#L24)

```python
assert_equal_with_reporter("expected", "actual", reporter)
```

but we also improve it to be up to date with current approvaltests `Options`

**Comment by isidore** [comment]
Improved for options with v8.2.0
