### ISSUE TITLE
Running tests with pytest and vimdiff requires "pytest -s"?

### ISSUE THREAD

**Issue by jsivak** [approvals/ApprovalTests.Python#40]
Howdy,

This is mainly a question on usage of approvaltests on Linux using vimdiff as the "diff-er".
When running with pytest, I find that I have to use "pytest -s" in order for vimdiff to be displayed during the test run. Is this the expected or prescribed way to use approval tests with pytest?

Thanks

**Comment by maxalbert** [comment]
This is expected. According to the pytest [docs](https://docs.pytest.org/en/latest/capture.html): "During test execution any output sent to stdout and stderr is captured." Therefore unless you specify the `-s` flag vimdiff won't receive any input from pytest (because it is captured) and won't be able to display anything.

There _may_ be a way for approvaltests to access the captured output of a test and feed this to the diff reporter (maybe using the [capsys](https://docs.pytest.org/en/latest/capture.html#accessing-captured-output-from-a-test-function) fixture or similar machinery), but it will need some careful consideration to avoid unintended side-effects for the user running the tests. I should mention that I'm not an approvaltests developer, so maybe I'm missing something obvious that would make this an easy fix.

**Comment by jsivak** [comment]
Thanks for the "confirmation" on the expected use of "pytest -s" and the pointer to `capsys`. If I get some free time I'll see what I can do with that..
